import "@/styles/globals.css";
import { Inter } from "next/font/google";
import ConfigProvider from "@/components/ConfigProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LOVE",
  description: "Generated by LOVE",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider>{children}</ConfigProvider>
      </body>
    </html>
  );
}
